- name: Uninstall website
  hosts: Moria
  tasks:
  - name: Remove Nginx config file for website
    become: true
    ansible.builtin.file:
      path: /data/nginx-config/website.conf
      state: absent
  - name: Remove source files
    become: true
    ansible.builtin.file:
      path: /data/nginx-static/website
      state: absent

  - name: Read homleab config
    ansible.builtin.slurp:
      src: '{{ansible_user_dir}}/.homelab.json'
    register: homelab_config_file
  - name: Set homelab_config variable
    ansible.builtin.set_fact:
      homelab_config: '{{homelab_config_file.content|b64decode|from_json}}'

  - name: Delete from Postgres table service_port
    community.postgresql.postgresql_query:
      login_host: '{{homelab_config.database.host}}'
      login_user: '{{homelab_config.database.user}}'
      login_password: '{{homelab_config.database.password}}'
      db: '{{homelab_config.database.name}}'
      query: 'DELETE FROM service_port WHERE service = %s;'
      positional_args:
      - website
  - name: Delete from Postgres table service
    community.postgresql.postgresql_query:
      login_host: '{{homelab_config.database.host}}'
      login_user: '{{homelab_config.database.user}}'
      login_password: '{{homelab_config.database.password}}'
      db: '{{homelab_config.database.name}}'
      query: 'DELETE FROM service WHERE name = %s;'
      positional_args:
      - website
